[workspace]
release_always = false
publish = true
git_only = false
dependencies_update = false
custom_minor_increment_regex = "^breaking$|^💥 breaking:"
changelog_update = false
git_release_enable = false
git_tag_name = "{{ package }}-v{{ version }}"

[[package]]
name = "cue-cli"
version_group = "cue"

[[package]]
name = "cue-client"
version_group = "cue"

[[package]]
name = "cue-core"
version_group = "cue"

[[package]]
name = "cue-daemon"
version_group = "cue"

[[package]]
name = "cue-language"
version_group = "cue"

[[package]]
name = "cue-protocol"
version_group = "cue"

[[package]]
name = "cue-runtime"
version_group = "cue"

[[package]]
name = "cue-store-sqlite"
version_group = "cue"

[[package]]
name = "cue-tui"
version_group = "cue"
